# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Fredrik on Github"
description: > # this means to ignore newlines until "email:"
   Fredriks code blog

name: 'Fredrik Olsen'
author: 'Fredrik Olsen'
author_image: "https://avatars1.githubusercontent.com/u/8249?v=3&s=80"

paginate:	5

url: "http://folsen.github.io" # the base hostname & protocol for your site
baseurl: ""
